### ISSUE TITLE
How to load the trained model？

### ISSUE THREAD

**Issue by 1llss** [TencentARC/T2I-Adapter#118]
I use the train_sketch.py ​​file given by the author to train on my own data set. The trained model weight file is a .pth file. The following error occurred when I loaded my trained model weights：
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    adapter.load_state_dict(state_dict)
  File "/opt/data/private/T2I-Adapter-XL/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for T2IAdapter:
        Missing key(s) in state_dict: "adapter.conv_in.weight", "adapter.conv_in.bias", "adapter.body.0.resnets.0.block1.weight", "adapter.body.0.resnets.0.block1.bias", "adapter.body.0.resnets.0.block2.weight", "adapter.body.0.resnets.0.block2.bias", "adapter.body.0.resnets.1.block1.weight", "adapter.body.0.resnets.1.block1.bias", "adapter.body.0.resnets.1.block2.weight", "adapter.body.0.resnets.1.block2.bias", "adapter.body.1.in_conv.weight", "adapter.body.1.in_conv.bias", "adapter.body.1.resnets.0.block1.weight", "adapter.body.1.resnets.0.block1.bias", "adapter.body.1.resnets.0.block2.weight", "adapter.body.1.resnets.0.block2.bias", "adapter.body.1.resnets.1.block1.weight", "adapter.body.1.resnets.1.block1.bias", "adapter.body.1.resnets.1.block2.weight", "adapter.body.1.resnets.1.block2.bias", "adapter.body.2.in_conv.weight", "adapter.body.2.in_conv.bias", "adapter.body.2.resnets.0.block1.weight", "adapter.body.2.resnets.0.block1.bias", "adapter.body.2.resnets.0.block2.weight", "adapter.body.2.resnets.0.block2.bias", "adapter.body.2.resnets.1.block1.weight", "adapter.body.2.resnets.1.block1.bias", "adapter.body.2.resnets.1.block2.weight", "adapter.body.2.resnets.1.block2.bias", "adapter.body.3.resnets.0.block1.weight", "adapter.body.3.resnets.0.block1.bias", "adapter.body.3.resnets.0.block2.weight", "adapter.body.3.resnets.0.block2.bias", "adapter.body.3.resnets.1.block1.weight", "adapter.body.3.resnets.1.block1.bias", "adapter.body.3.resnets.1.block2.weight", "adapter.body.3.resnets.1.block2.bias".
         Unexpected key(s) in state_dict: "body.0.block1.weight", "body.0.block1.bias", "body.0.block2.weight", "body.0.block2.bias", "body.1.block1.weight", "body.1.block1.bias", "body.1.block2.weight", "body.1.block2.bias", "body.2.in_conv.weight", "body.2.in_conv.bias", "body.2.block1.weight", "body.2.block1.bias", "body.2.block2.weight", "body.2.block2.bias", "body.3.block1.weight", "body.3.block1.bias", "body.3.block2.weight", "body.3.block2.bias", "body.4.in_conv.weight", "body.4.in_conv.bias", "body.4.block1.weight", "body.4.block1.bias", "body.4.block2.weight", "body.4.block2.bias", "body.5.block1.weight", "body.5.block1.bias", "body.5.block2.weight", "body.5.block2.bias", "body.6.block1.weight", "body.6.block1.bias", "body.6.block2.weight", "body.6.block2.bias", "body.7.block1.weight", "body.7.block1.bias", "body.7.block2.weight", "body.7.block2.bias", "conv_in.weight", "conv_in.bias"

![image](https://github.com/TencentARC/T2I-Adapter/assets/152993869/1e7ca1ae-212e-4f91-83b1-d8fc106b9424)
![image](https://github.com/TencentARC/T2I-Adapter/assets/152993869/02980dc0-3291-4789-bd73-5b07b159e545)

**Comment by JinShuwenABC** [comment]
Have you ever solved the problem? Does it mean diffuser pipe not support testing from self-training pth files? Maybe we have to change the key mentioned above.
