### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by ivanmikhnenkov** [TencentARC/T2I-Adapter#29]
Got an error running the following script: 
```
python3 test_adapter.py --which_cond openpose --cond_path examples/openpose/avatar_image.jpg --cond_inp_type image --prompt "Beautiful cyborg worman, mdjrny-v4 style" --sd_ckpt models/mdjrny-v4.ckpt --resize_short_edge 512 --cond_tau 1.0 --cond_weight 1.0 --n_samples 1 --adapter_ckpt models/t2iadapter_openpose_sd14v1.pth
```

after installing requirements with `pip install -r requirements.txt`. torch 1.13.1. All models are in correct directories. 
mdjrny-v4.ckpt is stable diffusion 1.v weights (https://huggingface.co/prompthero/openjourney).

full error:
```
['examples/openpose/avatar_image.jpg']
Loading model from models/mdjrny-v4.ckpt
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 64, 64) = 16384 dimensions.
making attention of type 'vanilla' with 512 in_channels
cuda
Traceback (most recent call last):
  File "test_adapter.py", line 80, in <module>
    main()
  File "test_adapter.py", line 56, in main
    cond_model = get_cond_model(opt, getattr(ExtraCondition, which_cond))
  File "/home/ivan/volume/txt2avatar/T2I-Adapter/ldm/modules/extra_condition/api.py", line 62, in get_cond_model
    model = OpenposeInference().to(opt.device)
  File "/home/ivan/volume/txt2avatar/T2I-Adapter/ldm/modules/extra_condition/openpose/api.py", line 26, in __init__
    self.body_estimation = Body(body_modelpath)
  File "/home/ivan/volume/txt2avatar/T2I-Adapter/ldm/modules/extra_condition/openpose/body.py", line 22, in __init__
    model_dict = util.transfer(self.model, torch.load(model_path))
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

```

**Comment by HeliosZhao** [comment]
Hi, I think it is the problem of openpose checkpoint [here](https://github.com/TencentARC/T2I-Adapter/blob/b324d9f74b3736a35f0178e2a26713bfb100d83d/ldm/modules/extra_condition/openpose/api.py#L13), which is broken. While the openpose checkpoint in [ControlNet repo](https://github.com/lllyasviel/ControlNet/blob/16ea3b5379c1e78a4bc8e3fc9cae8d65c42511b1/annotator/openpose/__init__.py#L12) works for me.

@MC-E Hi Chong, thanks for your great work. Can you update the openpose model in your hugging face repo?

**Comment by MC-E** [comment]
Hi, I think this is probably caused by incomplete downloading. This checkpoint works for our HuggingFace plateform https://huggingface.co/spaces/Adapter/T2I-Adapter. If any questions, please feel free to report back to us.
<img width="559" alt="捕获" src="https://user-images.githubusercontent.com/54032224/225493671-a2332622-837b-460b-8537-ce7dfbcbda5e.PNG">
